name: Deploy User Service to K3s

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: mash02/user-service
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create user-service-deployment.yaml
        shell: bash
        run: |
          cat <<EOF > user-service-deployment.yaml
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: user-service
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: user-service
            template:
              metadata:
                labels:
                  app: user-service
              spec:
                containers:
                - name: user-service
                  image: ${IMAGE_NAME}:${IMAGE_TAG}
                  ports:
                  - containerPort: 8080
                  envFrom:
                  - secretRef:
                      name: user-service-secret
          EOF

      - name: Write user-service-secret.yaml from GitHub Secret
        run: echo '${{ secrets.USER_SERVICE_SECRET_YAML }}' > user-service-secret.yaml

      - name: Check if files exist
        run: |
          ls -la
          echo "user-service-deployment.yaml:" && cat user-service-deployment.yaml
          echo "user-service-secret.yaml:" && cat user-service-secret.yaml || echo "Missing secret file"
          echo "user-service-service.yaml:" && cat user-service-service.yaml || echo "Missing service file"

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Install OpenSSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Set up SSH key (RSA)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'echo "SSH connection successful"'

      - name: Deploy to EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} "mkdir -p ~/deploy/user-service"
          scp user-service-*.yaml ubuntu@${{ secrets.EC2_HOST }}:~/deploy/user-service/
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/deploy/user-service
            sudo kubectl apply -f user-service-secret.yaml
            sudo kubectl apply -f user-service-deployment.yaml
            sudo kubectl apply -f user-service-service.yaml
          EOF
