name: Deploy User Service to K3s
on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: mash02/user-service
  IMAGE_TAG: latest
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create user-service-deployment.yaml
        shell: bash
        run: |
          cat << 'EOL' > user-service-deployment.yaml
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: user-service
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: user-service
            template:
              metadata:
                labels:
                  app: user-service
              spec:
                containers:
                - name: user-service
                  image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
                  ports:
                  - containerPort: 8080
                  envFrom:
                  - secretRef:
                      name: user-service-secret
          EOL
          
      - name: Check if files exist
        run: |
          ls -la
          echo "Checking if deployment and secret files exist:"
          [ -f user-service-deployment.yaml ] && echo "user-service-deployment.yaml exists" || echo "user-service-deployment.yaml MISSING"
          [ -f user-service-secret.yaml ] && echo "user-service-secret.yaml exists" || echo "user-service-secret.yaml MISSING"
          [ -f user-service-service.yaml ] && echo "user-service-service.yaml exists" || echo "user-service-service.yaml MISSING"
      - name: Write user-service-secret.yaml from GitHub Secret
        shell: bash
        run: |
          echo '${{ secrets.USER_SERVICE_SECRET_YAML }}' > user-service-secret.yaml
          
      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
      - name: Install OpenSSH client
        run: |
          apt-get update && apt-get install -y openssh-client

      - name: Setup SSH key with proper format
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "Setting up SSH key..."
          # Create a fresh key file
          > ~/.ssh/id_rsa
          # Set permissions before writing content
          chmod 600 ~/.ssh/id_rsa
          # Write the key with proper line handling
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          
          # Check key format and add debugging info
          echo "Key file stats:"
          ls -la ~/.ssh/id_rsa
          echo "First line of key (should be -----BEGIN...):"
          head -n 1 ~/.ssh/id_rsa | grep -v "BEGIN" && echo "ERROR: Missing BEGIN header" || echo "BEGIN header found"
          echo "Last line of key (should be -----END...):"
          tail -n 1 ~/.ssh/id_rsa | grep -v "END" && echo "ERROR: Missing END header" || echo "END header found"
          
          # Add host key to known hosts
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts 2>/dev/null
          
      - name: Test SSH connection
        run: |
          echo "Testing SSH connection with verbose output..."
          ssh -v -o "StrictHostKeyChecking=no" ubuntu@${{ secrets.EC2_HOST }} 'echo "SSH connection successful"'
      - name: Deploy to EC2 with SSH
        run: |
          # Ensure target directory exists
          ssh -o "StrictHostKeyChecking=no" ubuntu@${{ secrets.EC2_HOST }} 'mkdir -p /home/ubuntu/deploy/user-service'
          
          # Copy files
          echo "Copying YAML files to EC2..."
          scp -o "StrictHostKeyChecking=no" user-service-*.yaml ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/deploy/user-service/
          
          # Apply Kubernetes configurations
          echo "Applying Kubernetes configurations..."
          ssh -o "StrictHostKeyChecking=no" ubuntu@${{ secrets.EC2_HOST }} '
            cd /home/ubuntu/deploy/user-service && 
            kubectl apply -f user-service-secret.yaml && 
            kubectl apply -f user-service-deployment.yaml && 
            kubectl apply -f user-service-service.yaml
          '
