name: Deploy User Service to K3s

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: mash02/user-service
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create user-service-deployment.yaml
        shell: bash
        run: |
          cat << 'EOL' > user-service-deployment.yaml
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: user-service
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: user-service
            template:
              metadata:
                labels:
                  app: user-service
              spec:
                containers:
                - name: user-service
                  image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
                  ports:
                  - containerPort: 8080
                  envFrom:
                  - secretRef:
                      name: user-service-secret
          EOL

      - name: Create user-service-service.yaml
        shell: bash
        run: |
          cat << 'EOL' > user-service-service.yaml
          apiVersion: v1
          kind: Service
          metadata:
            name: user-service
            namespace: default
          spec:
            selector:
              app: user-service
            ports:
              - protocol: TCP
                port: 80
                targetPort: 8080
            type: ClusterIP
          EOL

      - name: Write user-service-secret.yaml from GitHub Secret
        shell: bash
        run: |
          printf "%s" "${{ secrets.USER_SERVICE_SECRET_YAML }}" > user-service-secret.yaml

      - name: Check if files exist
        run: |
          ls -la
          echo "Checking if deployment and secret files exist:"
          [ -f user-service-deployment.yaml ] && echo "user-service-deployment.yaml exists" || echo "user-service-deployment.yaml MISSING"
          [ -f user-service-secret.yaml ] && echo "user-service-secret.yaml exists" || echo "user-service-secret.yaml MISSING"
          [ -f user-service-service.yaml ] && echo "user-service-service.yaml exists" || echo "user-service-service.yaml MISSING"

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Install OpenSSH client
        run: |
          sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Setup SSH key with proper format
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts 2>/dev/null

      - name: Test SSH connection
        run: |
          echo "Testing SSH connection..."
          ssh -o "StrictHostKeyChecking=no" ubuntu@${{ secrets.EC2_HOST }} 'echo "SSH connection successful"'

      - name: Deploy to EC2 with SSH
        run: |
          ssh -o "StrictHostKeyChecking=no" ubuntu@${{ secrets.EC2_HOST }} 'mkdir -p /home/ubuntu/deploy/user-service'
          echo "Copying YAML files to EC2..."
          scp -o "StrictHostKeyChecking=no" user-service-*.yaml ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/deploy/user-service/
          echo "Applying Kubernetes configurations..."
          ssh -o "StrictHostKeyChecking=no" ubuntu@${{ secrets.EC2_HOST }} '
            cd /home/ubuntu/deploy/user-service && 
            kubectl apply -f user-service-secret.yaml && 
            kubectl apply -f user-service-deployment.yaml && 
            kubectl apply -f user-service-service.yaml && 
            kubectl rollout status deployment/user-service
          '
