name: Deploy User Service to K3s
on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: mash02/user-service
  IMAGE_TAG: latest
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create user-service-deployment.yaml
        shell: bash
        run: |
          cat << 'EOL' > user-service-deployment.yaml
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: user-service
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: user-service
            template:
              metadata:
                labels:
                  app: user-service
              spec:
                containers:
                - name: user-service
                  image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
                  ports:
                  - containerPort: 8080
                  envFrom:
                  - secretRef:
                      name: user-service-secret
          EOL
          
      - name: Check if files exist
        run: |
          ls -la
          echo "Checking if deployment and secret files exist:"
          [ -f user-service-deployment.yaml ] && echo "user-service-deployment.yaml exists" || echo "user-service-deployment.yaml MISSING"
          [ -f user-service-secret.yaml ] && echo "user-service-secret.yaml exists" || echo "user-service-secret.yaml MISSING"
          [ -f user-service-service.yaml ] && echo "user-service-service.yaml exists" || echo "user-service-service.yaml MISSING"
      - name: Write user-service-secret.yaml from GitHub Secret
        shell: bash
        run: |
          echo '${{ secrets.USER_SERVICE_SECRET_YAML }}' > user-service-secret.yaml
          
      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          
      - name: Copy manifests to EC2
        run: |
          scp user-service-*.yaml ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/deploy/user-service/
      - name: Deploy on EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} 'cd /home/ubuntu/deploy/user-service && \
          kubectl apply -f user-service-secret.yaml && \
          kubectl apply -f user-service-deployment.yaml && \
          kubectl apply -f user-service-service.yaml'
